[build]
  base = "nithin-gudala-portfolio"  # Set this to the subdirectory if needed
  publish = "dist"                  # The folder containing your built files (Vue default is dist/)
  command = "npm run build"         # Or "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
